default_language_version:
  python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: debug-statements
  - id: detect-private-key

- repo: https://github.com/asottile/pyupgrade
  rev: v3.7.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--profile, black]

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-docstrings
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-simplify

- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-gfm        # GitHub-Flavored Markdown
    - mdformat-black        # For code blocks

- repo: https://github.com/myint/docformatter
  rev: v1.7.5
  hooks:
  - id: docformatter
    args: [--in-place, --wrap-summaries, '88', --wrap-descriptions, '88']

- repo: https://github.com/hadialqattan/pycln
  rev: v2.2.2
  hooks:
  - id: pycln
    args: [--config=pyproject.toml]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
